/** Synthetic documentation-range data only; shared by offline DOM/browser QA. */
import { buildReportView } from "../../src/core/report-views";
const generatedAt = "2026-09-15T10:00:00.000Z";
const row = {
  name: "ether-uplink",
  type: "ether",
  flags: "R",
  mtu: "1500",
  "mac-address": "02:00:00:00:00:01",
};
const report = (
  kind: Parameters<typeof buildReportView>[0],
  tool: string,
  title: string,
  data: unknown,
) => ({ ...buildReportView(kind, tool, title, "branch-lab", JSON.stringify(data)), generatedAt });
export const VIEW_FIXTURES: Record<string, Record<string, unknown>> = {
  records: {
    __mikrotikView: "records",
    tool: "list_interfaces",
    title: "Network interfaces",
    kind: "list",
    format: "detail",
    columns: Object.keys(row),
    rows: [row, { ...row, name: "wg-transit", type: "wg", flags: "" }],
    flags: { R: "running" },
    count: 2,
    raw: "Interface inventory",
    generatedAt,
  },
  interfaces: {
    __mikrotikView: "interfaces",
    device: "branch-lab",
    rows: [
      row,
      { ...row, name: "wg-transit", type: "wg", flags: "", comment: "Site-to-site transit" },
      { ...row, name: "wifi-guests", type: "wifi", flags: "X" },
    ],
    flags: {},
    generatedAt,
  },
  firewall: {
    __mikrotikView: "firewall",
    device: "branch-lab",
    chain: "forward",
    rows: [
      {
        ".id": "*A",
        "#": "0",
        chain: "forward",
        action: "accept",
        "connection-state": "established,related",
        packets: "183920",
        bytes: "5439919",
      },
      {
        ".id": "*B",
        "#": "1",
        chain: "forward",
        action: "drop",
        "in-interface": "ether-uplink",
        comment: "Block unsolicited WAN traffic",
        packets: "238",
        bytes: "15360",
      },
    ],
    flags: {},
    generatedAt,
  },
  "firewall-audit": {
    __mikrotikView: "firewall-audit",
    device: "branch-lab",
    riskScore: 36,
    grade: "fair",
    counts: { high: 1, medium: 1, low: 0, total: 2 },
    ruleCount: 18,
    findings: [
      {
        kind: "broad",
        severity: "high",
        table: "filter",
        chain: "input",
        title: "Review broad management access",
        detail: "The rule permits management traffic without a source restriction.",
        suggestion: "Check the intended management network before changing this rule.",
      },
      {
        kind: "duplicate",
        severity: "medium",
        table: "filter",
        chain: "forward",
        title: "Duplicate filter candidate",
        detail: "Two captured rules have the same match conditions.",
        suggestion: "Compare counters and comments before removing either rule.",
      },
    ],
    generatedAt,
  },
  "connected-devices": {
    __mikrotikView: "connected-devices",
    devices: [
      {
        mac: "02:00:00:00:00:21",
        ip: "192.0.2.21",
        host: "Design workstation",
        iface: "ether-studio",
        server: "dhcp-lan",
        status: "bound",
        static: true,
        blocked: false,
        lastSeen: "4s",
        comment: "Studio",
      },
      {
        mac: "02:00:00:00:00:22",
        ip: "192.0.2.22",
        host: "Conference display",
        iface: "wifi-guests",
        server: "dhcp-guest",
        status: "bound",
        static: false,
        blocked: false,
        lastSeen: "9s",
        comment: "",
      },
    ],
    counts: { total: 2, blocked: 0, static: 1 },
    generatedAt,
  },
  dashboard: {
    device: "branch-lab",
    identity: "Studio gateway",
    resource: {
      version: "7.23.3",
      uptime: "18d 4h 22m",
      "cpu-count": "4",
      "architecture-name": "arm64",
      "board-name": "hAP ax3",
    },
    health: { temperature: "43" },
    routerboard: { model: "C53UiG+5HPaxD2HPaxD" },
    derived: {
      cpuLoadPct: 24,
      memUsedBytes: 268435456,
      memTotalBytes: 1073741824,
      memUsedPct: 25,
      hddUsedBytes: 33554432,
      hddTotalBytes: 134217728,
      hddUsedPct: 25,
      temperatureC: 43,
      voltageV: 24,
    },
    generatedAt,
  },
  aaa: {
    __mikrotikView: "aaa-section",
    slug: "radius",
    available: true,
    rows: [
      {
        ".id": "*1",
        address: "192.0.2.50",
        service: "ppp,login",
        "authentication-port": "1812",
        "accounting-port": "1813",
        disabled: "no",
      },
    ],
  },
  investigations: report("investigations", "get_investigation", "Client & service investigation", {
    client: "192.0.2.21",
    target: "payments.example.test",
    service: "Checkout availability",
    device: "branch-lab",
    clientOutcome: "unverified",
    createdAt: 1789466400000,
    evidence: [
      {
        device: "branch-lab",
        source: "bridge-host",
        state: "observed",
        summary: "Attachment record on ether-studio",
        rows: [{ interface: "ether-studio", bridge: "bridge-lan" }],
      },
      {
        device: "branch-lab",
        source: "router-ping",
        state: "unknown",
        summary: "Router probe unavailable",
        rows: [],
      },
    ],
    nextTests: [
      "Check the service from the actual client network.",
      "Compare the return path on the destination router.",
    ],
  }),
  "round-trip": report("round-trip", "trace_round_trip", "Forward & return path", {
    status: "unknown",
    liveDelivery: "unverified",
    asymmetric: true,
    forward: {
      status: "modelled",
      hops: [
        {
          device: "branch-lab",
          ingress: "bridge-lan",
          egress: "wg-transit",
          status: "modelled",
          reason: "Snapshot route selects the declared tunnel.",
        },
        {
          device: "edge-lab",
          ingress: "wg-branch",
          egress: "ether-uplink",
          status: "modelled",
          reason: "Modelled forward-chain acceptance.",
        },
      ],
    },
    reverse: {
      status: "unknown",
      hops: [
        {
          device: "edge-lab",
          ingress: "ether-uplink",
          egress: "wg-branch",
          status: "unknown",
          reason: "NAT boundary: reverse connection state is not modelled.",
        },
      ],
    },
    assumptions: [
      "Saved snapshots only; no packets were sent.",
      "The return leg assumes a replying host.",
    ],
    provenance: [
      {
        device: "branch-lab",
        snapshotId: "snapshot-lab-1",
        capturedAt: 1789466400000,
        sha: "fixture-sha",
      },
    ],
  }),
  "service-health": report("service-health", "run_service_contract", "Checkout service health", {
    device: "branch-lab",
    status: "fail",
    vantage: "mcp-host",
    checks: [
      {
        target: "checkout-dns",
        kind: "dns",
        status: "pass",
        durationMs: 21,
        detail: "Approved address resolved.",
      },
      {
        target: "checkout-https",
        kind: "https",
        status: "fail",
        durationMs: 504,
        detail: "Expected HTTP 200, received HTTP 503.",
      },
      {
        target: "checkout-tls",
        kind: "tls",
        status: "unknown",
        durationMs: 0,
        detail: "No certificate evidence available.",
      },
    ],
  }),
  fabric: report("fabric", "map_l2_fabric", "Layer-2 fabric", {
    device: "branch-lab",
    stats: { ports: 2, hosts: 3, accessPorts: 1, uplinks: 1, unidentified: 0 },
    ports: [
      {
        interface: "ether-studio",
        bridge: "bridge-lan",
        role: "access",
        hostCount: 1,
        hosts: [
          {
            label: "Design workstation",
            ip: "192.0.2.21",
            mac: "02:00:00:00:00:21",
            nameSource: "dhcp",
          },
        ],
      },
      {
        interface: "ether-core",
        bridge: "bridge-lan",
        role: "uplink",
        hostCount: 2,
        peerIdentity: "Floor switch",
        hosts: [
          {
            label: "Floor switch",
            ip: "192.0.2.2",
            mac: "02:00:00:00:00:02",
            nameSource: "neighbor",
          },
          {
            label: "Conference display",
            ip: "192.0.2.22",
            mac: "02:00:00:00:00:22",
            nameSource: "dhcp",
          },
        ],
      },
    ],
  }),
  operations: report("operations", "plan_changes", "Coordinated change preview", {
    state: "planned",
    commands: [
      {
        command: "/ip route print",
        risk: "READ",
        explanation: "Inspect the current route evidence.",
      },
    ],
    warnings: ["Preview only. No configuration was changed."],
    participants: ["branch-lab", "edge-lab"],
  }),
  reports: report("reports", "run_compliance_audit", "Security compliance evidence", {
    score: 82,
    status: "warn",
    findings: [
      {
        title: "Management source restriction",
        status: "fail",
        severity: "high",
        detail: "Management should be restricted to an explicit operator network.",
      },
      {
        title: "DNS resolver exposure",
        status: "pass",
        detail: "The evaluated rule set restricts unsolicited external DNS requests.",
      },
      {
        title: "Certificate evidence",
        status: "unknown",
        detail: "No certificate data was collected.",
      },
    ],
  }),
};
